---

NODE_ACCESS_WAIT_TIME: 5400
CORTX_ISO_FOLDER: '/opt/isos/' 


required_vars:
  - REIMAGE
  - NODE1
  - NODE2
  - CONFIG_URL
  - CORTX_BUILD_ISO_URL
  - CORTX_OS_ISO_URL
  - CORTX_PREP_URL
  - CLUSTER_PASS
  - SATELLITE_UN
  - SATELLITE_PW
  - CHANGE_PASS