version: "3"

services:
  eosjenkins-prod:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - /mnt/bigstorage/jenkins-dev/jenkins/jenkins-home:/var/jenkins_home
      - /mnt/bigstorage/:/mnt/bigstorage
    environment:
      - JAVA_OPTS=-Xmx4096m

