version: "3"

services:
  eosjenkins-dev:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - /mnt/jenkins-dev:/var/jenkins_home
      - /mnt/bigstorage/:/mnt/bigstorage
    environment:
      - JAVA_OPTS=-Xmx3072m
