---

- name: "[deploy-prep] : Remove volume_groups and reboot - primary node" 
  script: files/storage_fix.sh
  ignore_errors: true
  become: true
  delegate_to: "srvnode-1"

- name: "[deploy-prep] : Remove volume_groups and reboot - secondary node" 
  script: files/storage_fix.sh
  ignore_errors: true
  become: true
  delegate_to: "srvnode-2"

- name: "[deploy-prep] : Wait for server to restart"
  wait_for:
      host={{ hostvars[item]['ansible_host'] }}
      port=22
      delay=30
      timeout=1800
  become: false
  ignore_errors: true
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Create dir '/opt/isos/'"
  file: path=/opt/isos/ state=directory
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Download single ISO " 
  get_url:
    url: "{{ CORTX_BUILD_ISO_URL }}"
    dest: /opt/isos/{{ CORTX_BUILD_ISO_URL | basename }}
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Download OS ISO " 
  get_url:
    url: "{{ CORTX_OS_ISO_URL }}"
    dest: /opt/isos/{{ CORTX_OS_ISO_URL | basename }}
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Download cortx_prep.sh script on both nodes" 
  get_url:
    url: "{{ CORTX_PREP_URL }}"
    dest: /opt/isos/{{ CORTX_PREP_URL | basename }}
    mode: '0755'
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Run  cortx_prep.sh on primary node" 
  command: /opt/isos/{{ CORTX_PREP_URL | basename }}
  ignore_errors: true
  become: true
  delegate_to: "srvnode-1"

- name: "[deploy-prep] : Wait for nodes to reboot"
  wait_for:
      host={{ hostvars[item]['ansible_host'] }}
      port=22
      delay=30
      timeout=1800
  become: false
  ignore_errors: true
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prep] : Download config file on primary node"
  get_url:
    url: "{{ CONFIG_URL }}"
    dest: /root/config.ini
    mode: '0754'
  delegate_to: "srvnode-1"

